//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketlerTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketlerTB()
        {
            this.AnketCevapTB = new HashSet<AnketCevapTB>();
        }
    
        public int id { get; set; }
        public string soru { get; set; }
        public string cevap { get; set; }
        public string cevap2 { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> sinifid { get; set; }
        public Nullable<System.DateTime> son_tarih { get; set; }
        public Nullable<int> argorid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevapTB> AnketCevapTB { get; set; }
        public virtual ArgorTB ArgorTB { get; set; }
        public virtual SanalSinifTB SanalSinifTB { get; set; }
    }
}
