//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgorTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArgorTB()
        {
            this.AnketlerTB = new HashSet<AnketlerTB>();
            this.DuyurularTB = new HashSet<DuyurularTB>();
            this.OgrenciTB = new HashSet<OgrenciTB>();
            this.SanalSinifTB = new HashSet<SanalSinifTB>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public Nullable<System.DateTime> kayit { get; set; }
        public Nullable<int> uniid { get; set; }
        public Nullable<System.DateTime> songiris { get; set; }
        public Nullable<int> adminid { get; set; }
    
        public virtual AdminTB AdminTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketlerTB> AnketlerTB { get; set; }
        public virtual UniversiteTB UniversiteTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuyurularTB> DuyurularTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciTB> OgrenciTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanalSinifTB> SanalSinifTB { get; set; }
    }
}
