//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyuru_GorenlerTB
    {
        public int id { get; set; }
        public Nullable<int> ogr_id { get; set; }
        public Nullable<int> duyuru_id { get; set; }
    
        public virtual DuyurularTB DuyurularTB { get; set; }
        public virtual OgrenciTB OgrenciTB { get; set; }
    }
}
