//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyurularTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DuyurularTB()
        {
            this.Duyuru_GorenlerTB = new HashSet<Duyuru_GorenlerTB>();
        }
    
        public int id { get; set; }
        public string baslik { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> sinifid { get; set; }
        public Nullable<int> argoid { get; set; }
    
        public virtual ArgorTB ArgorTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyuru_GorenlerTB> Duyuru_GorenlerTB { get; set; }
        public virtual SanalSinifTB SanalSinifTB { get; set; }
    }
}
