//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelenMesajTB
    {
        public int id { get; set; }
        public Nullable<int> kisiid { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual OgrenciTB OgrenciTB { get; set; }
    }
}
