//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odev_GorulduTB
    {
        public int id { get; set; }
        public Nullable<int> ogrenciid { get; set; }
        public Nullable<int> odev_id { get; set; }
        public Nullable<bool> goruldu { get; set; }
        public Nullable<System.DateTime> gormetarih { get; set; }
    
        public virtual OdevlerTB OdevlerTB { get; set; }
        public virtual OgrenciTB OgrenciTB { get; set; }
    }
}
