//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciTB()
        {
            this.AnketCevapTB = new HashSet<AnketCevapTB>();
            this.Duyuru_GorenlerTB = new HashSet<Duyuru_GorenlerTB>();
            this.GelenMesajTB = new HashSet<GelenMesajTB>();
            this.GonderilenMesajTB = new HashSet<GonderilenMesajTB>();
            this.Odev_GorulduTB = new HashSet<Odev_GorulduTB>();
            this.Odev_TeslimTB = new HashSet<Odev_TeslimTB>();
            this.SinifOgrencilerTB = new HashSet<SinifOgrencilerTB>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public Nullable<System.DateTime> ilkkayit { get; set; }
        public Nullable<System.DateTime> sonaktif { get; set; }
        public Nullable<int> argorid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevapTB> AnketCevapTB { get; set; }
        public virtual ArgorTB ArgorTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyuru_GorenlerTB> Duyuru_GorenlerTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelenMesajTB> GelenMesajTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMesajTB> GonderilenMesajTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odev_GorulduTB> Odev_GorulduTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odev_TeslimTB> Odev_TeslimTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinifOgrencilerTB> SinifOgrencilerTB { get; set; }
    }
}
