//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanalSinifTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanalSinifTB()
        {
            this.AnketlerTB = new HashSet<AnketlerTB>();
            this.DuyurularTB = new HashSet<DuyurularTB>();
            this.OdevlerTB = new HashSet<OdevlerTB>();
            this.SinifOgrencilerTB = new HashSet<SinifOgrencilerTB>();
        }
    
        public int id { get; set; }
        public string sinifadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
        public Nullable<int> argorid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketlerTB> AnketlerTB { get; set; }
        public virtual ArgorTB ArgorTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuyurularTB> DuyurularTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdevlerTB> OdevlerTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinifOgrencilerTB> SinifOgrencilerTB { get; set; }
    }
}
