//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinifOgrencilerTB
    {
        public int id { get; set; }
        public Nullable<int> ogrid { get; set; }
        public Nullable<int> sinifid { get; set; }
        public Nullable<bool> ogr_katilim { get; set; }
        public Nullable<System.DateTime> katilimtarih { get; set; }
        public Nullable<bool> sessiz { get; set; }
    
        public virtual OgrenciTB OgrenciTB { get; set; }
        public virtual SanalSinifTB SanalSinifTB { get; set; }
    }
}
