//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINIFIM.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversiteTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniversiteTB()
        {
            this.ArgorTB = new HashSet<ArgorTB>();
        }
    
        public int id { get; set; }
        public string universite { get; set; }
        public Nullable<int> adminid { get; set; }
    
        public virtual AdminTB AdminTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArgorTB> ArgorTB { get; set; }
    }
}
